# Generated by Django 4.2.10 on 2024-05-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_name', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
