# Generated by Django 4.2.10 on 2024-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rounds_round_id_team_team_id_alter_rounds_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=20)),
                ('quset_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.AddField(
            model_name='rounds',
            name='quests',
            field=models.ManyToManyField(to='main_app.quset'),
        ),
    ]
