# Generated by Django 4.2.10 on 2024-05-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_quset_rename_name_team_team_name_rounds_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='quset',
            name='ans',
            field=models.CharField(default='', max_length=25),
        ),
    ]
